server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    gateway:
      default-filters:
      - name: KeyIdAuthentication
        args:
          anonymous-url-patterns: /send-account-management-email-func-v2/api/v2/send-reset-password-email
      - name: ServiceToServiceAuthentication
      - name: Retry
        args:
          retries: 20
          statuses: INTERNAL_SERVER_ERROR
      routes:

### auth ###

      - id: v2_set_roles
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/set-roles
        - Method=POST
        filters:
        - RewritePath=/api/v2/set-roles, /set-roles-func-v2/api/v2/set-roles

### gym ###

      - id: v2_cu_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/gym, /gym-func-v2/api/v2/gym
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_cud_gym_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/gym/events, /event-func-v2/api/v2/gym/events
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_cud_gym_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/gym/subscription-plans, /subscription-plan-func-v2/api/v2/gym/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_r_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym, /gym-func-v2/api/v2/gym
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_gym_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/events
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym/events, /event-func-v2/api/v2/gym/events
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_gym_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym/subscription-plans, /subscription-plan-func-v2/api/v2/gym/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### personal trainer ###

      - id: v2_cu_personal_trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/personal-trainer, /personal-trainer-func-v2/api/v2/personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_cud_personal_trainer_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/personal-trainer/events, /event-func-v2/api/v2/personal-trainer/events
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_cud_personal_trainer_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/personal-trainer/subscription-plans, /subscription-plan-func-v2/api/v2/personal-trainer/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_r_personal_trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer, /personal-trainer-func-v2/api/v2/personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_personal_trainer_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/events
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer/events, /event-func-v2/api/v2/personal-trainer/events
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_personal_trainer_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer/subscription-plans, /subscription-plan-func-v2/api/v2/personal-trainer/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### student ###

      - id: v2_cu_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/student
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/student, /student-func-v2/api/v2/student
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v2_r_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/student
        - Method=GET
        filters:
        - RewritePath=/api/v2/student, /student-func-v2/api/v2/student
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### sport ###

      - id: v2_sport_cud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/sport
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/sport, /sport-func-v2/api/v2/sport
        - name: RoleAuthorization
          args:
            roles: ROLE_ADMIN

      - id: v2_sport_r
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/sport
        - Method=GET
        filters:
        - RewritePath=/api/v2/sport, /sport-func-v2/api/v2/sport
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### focus ###

      - id: v2_focus_cud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/focus
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/focus, /focus-func-v2/api/v2/focus
        - name: RoleAuthorization
          args:
            roles: ROLE_ADMIN

      - id: v2_focus_r
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/focus
        - Method=GET
        filters:
        - RewritePath=/api/v2/focus, /focus-func-v2/api/v2/focus
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### fights ###

      - id: v2_fight_cud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/fight
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/fight, /fight-func-v2/api/v2/fight
        - name: RoleAuthorization
          args:
            roles: ROLE_ADMIN

      - id: v2_fight_r
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/fight
        - Method=GET
        filters:
        - RewritePath=/api/v2/fight, /fight-func-v2/api/v2/fight
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### locations ###

      - id: v2_locations
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/locations
        - Method=GET
        filters:
        - RewritePath=/api/v2/locations, /locations-func-v2/api/v2/locations
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### account management emails ###

      - id: v2_send_sign_up_verify_email
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/send-sign-up-verify-email
        - Method=POST
        filters:
        - RewritePath=/api/v2/send-sign-up-verify-email, /send-account-management-email-func-v2/api/v2/send-sign-up-verify-email

      - id: v2_send_reset_password_email
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/send-reset-password-email
        - Method=POST
        filters:
        - RewritePath=/api/v2/send-reset-password-email, /send-account-management-email-func-v2/api/v2/send-reset-password-email
